export const cartDefaults = {
  id: "",
  restaurant: {
    id: "",
    name: "",
    slug: "",
    description: "",
    street_address: "",
    building_number: "",
    postcode: "",
    city: "",
    state: "",
    country: "",
    latitude: 0,
    longitude: 0,
    phone_number: "",
    email: "",
    min_amount: 0,
    delivery_fee: 0,
    service_fee: 0,
    min_delivery_time: 0,
    max_delivery_time: 0,
    logo: "",
    cover: "",
    is_approved: true,
    force_close: false,
    created_at: "",
    updated_at: "",
    full_address: "",
    is_open: true,
  },
  total_items: 0,
  total_unique_items: 0,
  cart_total: 0,
  items: [
    {
      id: "",
      menu_category_id: "",
      name: "",
      description: "",
      price: 0,
      image: "",
      is_available: true,
      quantity: 0,
      item_total: 0,
      created_at: "",
      updated_at: "",
    },
  ],
};
