services:
  web:
    container_name: frontend
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    develop:
      watch:
        - path: ./backend/composer.json
          action: rebuild
        - path: ./backend/composer.lock
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  queue-worker:
    container_name: queue
    depends_on:
      - api
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    command: php artisan queue:work

  reverb:
    container_name: reverb
    depends_on:
      - api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    command: php artisan reverb:start

  pail:
    container_name: pail
    depends_on:
      - api
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    command: php artisan pail --timeout=0

  db:
    image: postgres:16.10-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: quickbite
      POSTGRES_USER: quickbite
      POSTGRES_PASSWORD: quickbite
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
