export const baseOffsetPaginationDefaults = {
  current_page: 1,
  data: [],
  first_page_url: "",
  from: null,
  last_page: 1,
  last_page_url: "",
  links: [],
  next_page_url: null,
  path: "",
  per_page: 15,
  prev_page_url: null,
  to: null,
  total: 0,
};
