import { baseOffsetPaginationDefaults } from "@/lib/query-defaults";

export const orderDefaults = {
  id: "",
  user_id: "",
  restaurant_id: "",
  order_code: 0,
  first_name: "",
  last_name: "",
  phone_number: "",
  street_address: "",
  building_number: "",
  postcode: "",
  city: "",
  state: "",
  country: "Italy",
  delivery_time: "",
  notes: null,
  payment_method: "cash",
  subtotal: 0,
  delivery_fee: 0,
  service_fee: 0,
  discount_rate: 0,
  discount: 0,
  total: 0,
  status: "pending",
  created_at: "",
  updated_at: "",
  order_items: [],
  restaurant: {
    id: "",
    name: "",
    slug: "",
    description: "",
    street_address: "",
    building_number: "",
    postcode: "",
    city: "",
    state: "",
    country: "",
    latitude: 0,
    longitude: 0,
    phone_number: "",
    email: "",
    min_amount: 0,
    delivery_fee: 0,
    service_fee: 0,
    min_delivery_time: 0,
    max_delivery_time: 0,
    logo: "",
    cover: "",
    is_approved: false,
    force_close: false,
    created_at: "",
    updated_at: "",
    full_address: "",
    is_open: false,
    reviews: [],
  },
};

export const ordersDefaults = baseOffsetPaginationDefaults;
